### PR TITLE
feat(farcaster): add farcaster resolver

### PR DESCRIPTION
**Pull request by developerfred**
#180

I created an api to correlate addresses with FIDs, so we can get images or any other information

https://github.com/developerfred/far-users

This solution is consuming API

### CODE REVIEW

**Comment by bonustrack** [comment]
We would prefer to use an API with some guarantee it will be maintained for a long time.

**Comment by developerfred** [comment]
@bonustrack do you have neynar key ?

**Comment by bonustrack** [comment]
@developerfred No, I'll create one, but be aware there is another person selected for the bounty https://github.com/snapshot-labs/stamp/issues/180#issuecomment-2028782668 I don't recommend continue on the PR unless it's not working with the other person.

**Comment by developerfred** [comment]
> @developerfred No, I'll create one, but be aware there is another person selected for the bounty [#180 (comment)](https://github.com/snapshot-labs/stamp/issues/180#issuecomment-2028782668) I don't recommend continue on the PR unless it's not working with the other person.

Its ok, I'll wait. I get the data from the warcast api, and send it to supabase, I have a query for fnames also in this api. ref: https://github.com/snapshot-labs/stamp/issues/194

I'm going to put the scraping code in the api too to make it easier for everyone to understand

```
query Query($address: String!) {
  getFnamesByAddress(address: $address) 
  {    
    name,
    fname,
    fid
  }
  
}```

graphql: https://far-users.vercel.app/api/graphql

**Comment by bonustrack** [comment]
@developerfred If you want to do #194 here is an example with Lens: https://github.com/snapshot-labs/stamp/blob/master/src/addressResolvers/lens.ts it must support querying multiple addresses. We should also use the same API (Neynar) for both resolving avatar and domain.

**Comment by developerfred** [comment]
https://github.com/snapshot-labs/stamp/assets/57037080/eb346429-36b4-40bd-a2be-7db825be3a68

**Review by wa0x6e — CHANGES_REQUESTED** [review]

**Comment by developerfred** [comment]
done ✅ 
```
 PASS  test/integration/resolvers/farcaster.test.ts
  farcaster
    user details by address
      ✓ should return false for invalid or non-existent addresses (135 ms)
      ✓ should return false if user details cannot be fetched (18 ms)
      ✓ should return a Buffer if user details are successfully fetched and the user has a profile picture (286 ms)
      ```

**Review by wa0x6e — APPROVED** [review]
tAck

**Pull request merged**
