### PR TITLE
feat: add support for starknet avatar

### LINKED ISSUE #175: feat: resolve starknet avatar
See https://docs.starknet.id/devs/starknetid-api#domain-to-data

### PR DESCRIPTION
**Pull request by wa0x6e**
Add support for Starknet avatar from domain (see https://docs.starknet.id/devs/starknetid-api#domain-to-data)

Fix #175 

Test with 

- http://localhost:3008/avatar/checkpoint.stark
- http://localhost:3008/avatar/0x07FF6B17f07c4d83236E3Fc5f94259A19D1Ed41bBCf1822397EA17882E9b038d

Should return the same image

Coming later in another PR: resolving Starknet avatar from address

### CODE REVIEW

**Comment by bonustrack** [comment]
Will it work with address too? Like https://cdn.stamp.fyi/avatar/0x07FF6B17f07c4d83236E3Fc5f94259A19D1Ed41bBCf1822397EA17882E9b038d (checkpoint.stark)

**Comment by wa0x6e** [comment]
Address coming later

**Comment by wa0x6e** [comment]
> Will it work with address too? Like https://cdn.stamp.fyi/avatar/0x07FF6B17f07c4d83236E3Fc5f94259A19D1Ed41bBCf1822397EA17882E9b038d (checkpoint.stark)

Added in this same PR

**Review by ChaituVR — CHANGES_REQUESTED** [review]
if you go here http://localhost:3008/avatar/0x07FF6B17f07c4d83236E3Fc5f94259A19D1Ed41bBCf1822397EA17882E9b038d
It display this image
image

If you go here http://localhost:3008/avatar/x.stark it is not same. is it expected?

**Comment by ChaituVR** [comment]
> Test with

> http://localhost:3008/avatar/checkpoint.stark
> http://localhost:3008/avatar/0x07FF6B17f07c4d83236E3Fc5f94259A19D1Ed41bBCf1822397EA17882E9b038d
> Should return the same image

I see different images

**Comment by wa0x6e** [comment]
> if you go here http://localhost:3008/avatar/0x07FF6B17f07c4d83236E3Fc5f94259A19D1Ed41bBCf1822397EA17882E9b038d It display this image image
> 
> If you go here http://localhost:3008/avatar/x.stark it is not same. is it expected?

Should be not the same, since they're not x.stark do not have an avatar set, so it fallback to blockie

**Comment by ChaituVR** [comment]
Untitled
Maybe we should remove this test case as it can take forever

**Comment by ChaituVR** [comment]
Also adding some timeout for fetch can be good idea

**Comment by wa0x6e** [comment]
> Also adding some timeout for fetch can be good idea

Every outgoing `fetch` call have a timeout of 5seconds, set via `axiosDefaultParams`

**Comment by wa0x6e** [comment]
> Untitled Maybe we should remove this test case as it can take forever

Used another domain/address for the tests, which does not use their slow IPFS resolver.

**Pull request merged**
