### PR TITLE
feat: add Farcaster avatar as resolver

### PR DESCRIPTION
**Pull request by Mr94t3z**
### Description:
This pull request introduces resolver functions for fetching Farcaster avatars associated with Ethereum addresses using Neynar APIs. Additionally, a test for the Farcaster resolver has been added.

### Changes Made:
- Added resolver functions for Farcaster avatars.
- Add a test for Farcaster resolver.

### CODE REVIEW

**Comment by bonustrack** [comment]
We **should not** replace Lens resolver, there should be both Lens and Farcaster. The integration here is incomplete have you tried it locally?

**Comment by Mr94t3z** [comment]
Actually, i got this error when i run the app 👇🏻
```bash
Error: Cannot find module '../build/Release/canvas.node'
```

**Comment by Mr94t3z** [comment]
It's working!

> Go to route:

```bash
http://localhost:3008/avatar/0xcB46Bfb7315eca9ECd42D02C1AE174DA4BBFf291
```

The result is the avatar that use on my Farcaster account, I guess it's working isn't it?

Screenshot 2024-03-31 at 4 58 41 PM

**Comment by bonustrack** [comment]
I think this API is not live updated, doesnt work for my adress for example: https://searchcaster.xyz/api/profiles?connected_address=0xeF8305E140ac520225DAf050e2f71d5fBcC543e7 . You once again integrated the resolver within Lens resolver

**Comment by Mr94t3z** [comment]
@bonustrack when is your wallet connected to your Farcaster account? If 1 or 2 days ago it's could be take a couple day I think.

**Comment by Mr94t3z** [comment]
> I think this API is not live updated, doesnt work for my adress for example: https://searchcaster.xyz/api/profiles?connected_address=0xeF8305E140ac520225DAf050e2f71d5fBcC543e7 . You once again integrated the resolver within Lens resolver

I'm still didn't get it, what do you mean by "I do again integrated the resolver within Lens resolver"?

**Comment by Mr94t3z** [comment]
The versioning API is now I think realtime. Please let me know where's wrong code did you mean by `We should not replace Lens resolver, there should be both Lens and Farcaster`. Thanks!

Screenshot 2024-03-31 at 8 34 50 PM

**Comment by bonustrack** [comment]
Each resolver should have their own file, currently you are adding Farcaster resolver within Lens file

**Comment by Mr94t3z** [comment]
I thought you want to change the code on Lens, at least you mentioned that in the issue page. Actually I can do that, but you've already choose another dev.

**Pull request closed without merging**
