### PR TITLE
feat: handle Matic token icon

### PR DESCRIPTION
**Pull request by Sekhmet**
## Test plan

Check http://localhost:3000/token/eip155:137:0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee?s=64 returns Matic icon.

### CODE REVIEW

**Comment by bonustrack** [comment]
Would this work with short names (EIP-3770)?

**Comment by bonustrack** [comment]
This returns Ethereum logo for me somehow http://localhost:3000/token/eip155:137:0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee?s=64
Same with short names.

**Comment by Sekhmet** [comment]
@bonustrack doesn't for me:
image

**Review by bonustrack — APPROVED** [review]
Disabled cache and reset node_modules it's still same for me but we can test in prod.

**Comment by Sekhmet** [comment]
Looks like AWS somehow caches it.

**Pull request merged**
