### PR TITLE
fix: raise error when AWS client is not configured

### PR DESCRIPTION
**Pull request by wa0x6e**
Raise error when AWS client is not configured, for better error stacktrace

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]
utAck

**Comment by ChaituVR** [comment]
Looks like test cases are failing though

**Comment by wa0x6e** [comment]
> Looks like test cases are failing though

Looks like starknet ID api changed, and does not return `img_url` anymore

```
https://api.starknet.id/domain_to_data?domain=fricoben.stark
```

```
{
"id": "0x000000000000000000000000000000000000000000000000000000cf4759fe9f",
"owner": "0x07ff6b17f07c4d83236e3fc5f94259a19d1ed41bbcf1822397ea17882e9b038d",
"main": false,
"creation_date": 1680431850,
"domain": {
"domain": "checkpoint.stark",
"migrated": false,
"root": true,
"creation_date": 1680431850,
"expiry": 1775039850,
"resolver": null,
"legacy_address": "0x07ff6b17f07c4d83236e3fc5f94259a19d1ed41bbcf1822397ea17882e9b038d",
"rev_address": "0x07ff6b17f07c4d83236e3fc5f94259a19d1ed41bbcf1822397ea17882e9b038d"
},
"user_data": [],
"verifier_data": [
{
"verifier": "0x06ac597f8116f886fa1c97a23fa4e08299975ecaf6b598873ca6792b9bbfb678",
"field": "0x000000000000000000000000000000000000000000000000000000006e616d65",
"data": "0x05d238f6103ead75507327b4948730addc934d9dbd7c3309b96b19e8cf136cef"
},
{
"verifier": "0x070aaa20ec4a46da57c932d9fd89ca5e6bb9ca3188d3df361a32306aff7d59c7",
"field": "0x00000000000000000000000000000000006e66745f70705f636f6e7472616374",
"data": "0x0727a63f78ee3f1bd18f78009067411ab369c31dece1ae22e16f567906409905"
}
],
"extended_verifier_data": [
{
"verifier": "0x070aaa20ec4a46da57c932d9fd89ca5e6bb9ca3188d3df361a32306aff7d59c7",
"field": "0x00000000000000000000000000000000000000000000006e66745f70705f6964",
"extended_data": [
"0x00000000000000000000000000000000000000000000000000000000000008b6",
"0x0000000000000000000000000000000000000000000000000000000000000000"
]
}
]
}
```

**Comment by wa0x6e** [comment]
Will merge this one, and fix the starknet issue in another PR

**Pull request merged**
